### PR TITLE
[Globalization] Support intl version game launching

### PR DESCRIPTION
**Pull request by solacens**
image
國際服Registry去找遊戲路徑似乎不適用，我就不改了。

啟動遊戲各個選項貌似都正常運作，估計就程序名字不同。

話說我本來就是在找有沒有Borderless windows的方法才找到這的哈哈，還有MAUI裝了我一大堆Tools。

### CODE REVIEW

**Comment by solacens** [comment]
至於有關角色什麼的我還要再看一下

**Comment by solacens** [comment]
Pipeline failed 應該是目前main的問題
就交給你們了

**Comment by Lightczx** [comment]
另外需要实现下 UnityLogGameLocator的国际服形式

**Comment by solacens** [comment]
How to trigger logics in UnityLogGameLocator?

**Comment by Lightczx** [comment]
> 



> How to trigger logic in UnityLogGameLocator?

In GameService.GetGamePathAsync 
If you want to directly trigger it you can modify some code in this method.

**Comment by solacens** [comment]
What should be the official way triggering it? The logic is modified but I would like to have a proper test.

**Comment by Lightczx** [comment]
> What should be the official way triggering it? The logic is modified but I would like to have a proper test.

No gamePath in database,click the webcache command button in gacha log page

**Comment by solacens** [comment]
Looks good on my side. Any side effects on the original logic?

**Comment by Lightczx** [comment]
> Manual tests look good on my side. Any side effects on the original logic?

Did you test gacha page?

**Comment by solacens** [comment]
image
用緩存刷新能拿到Game path
只是沒有數據出現 這部份我要另外再看差別在哪

**Comment by Lightczx** [comment]
I will merge the launch logic first.
Web requesting is refactoring and not suitable for outside changes currently

**Pull request merged**
