### PR TITLE
fix user log in/register/unregister/reset password info bar translation; fix #1088

### LINKED ISSUE #1088: [Bug]: 登录成功等弹窗未翻译
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22635.2700

### Snap Hutao 版本

1.7.16

### 设备 ID

_No response_

### 问题分类

用户界面

### 发生了什么？

在登录成功时产生的弹窗的结果未翻译
屏幕截图 2023-11-11 143944
查看代码后发现弹窗直接使用了服务端的返回值
屏幕截图 2023-11-11 145755
其它的一些代码也存在直接使用未翻译的返回值的情况

### 你期望发生的行为？

弹窗内容应当在客户端解析返回值后显示对应语言的信息

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

### PR DESCRIPTION
**Pull request by Tangweirui2021**
修正用户登录、注册、注销、重设密码时的弹窗的翻译问题

### CODE REVIEW

**Comment by Masterain98** [comment]
Fix #1088

**Comment by Lightczx** [comment]
There is a HutaoResponse and HutaoResponse<T> class, use them, and don't add extra translation items

**Comment by Tangweirui2021** [comment]
Sorry, I don't really understand. The function GetLocalizationMessageOrDefault in HutaoResponse need LocalizationKey to get the right translation,. Howerver, the response does not contain the LocalizationKey and there is no corresponding translation in translation items.

**Comment by Lightczx** [comment]
@Tangweirui2021 Sorry for that, it need a server patch first

**Comment by Tangweirui2021** [comment]
OK, please let me know when it's done.

**Comment by Lightczx** [comment]
BTW you should create PR against the `develop` branch

**Comment by Tangweirui2021** [comment]
My bad, I'll create a new one when the server is ready

**Comment by Lightczx** [comment]
Do you have XamlStyler installed for your VS? please format the resx before you create your next PR.😂

**Comment by Tangweirui2021** [comment]
OK, I'll install it. Sorry for that. I'm a beginner, thus I don't know much about how to create a PR. :(

**Comment by Lightczx** [comment]
> OK, I'll install it. Sorry for that. I'm a beginner, thus I don't know much about how to create a PR. :(

Nevermind, I'll handle it before I merge.

**Comment by Lightczx** [comment]
The server patch is online
I add several Key to the reponse body
```
ServerPassportRegisterSucceed
ServerPassportLoginSucceed
ServerPassportUnregisterSucceed
ServerPassportResetPasswordSucceed
```

@Tangweirui2021

**Comment by Tangweirui2018** [comment]
> The server patch is online I add several Key to the reponse body
> 
> ```
> ServerPassportRegisterSucceed
> ServerPassportLoginSucceed
> ServerPassportUnregisterSucceed
> ServerPassportResetPasswordSucceed
> ```
> 
> @Tangweirui2021

A new PR is there now, please check it.
#1090

**Pull request closed without merging**
